server:
  port: 18093
  servlet:
    context-path: /springcoming
spring:
  application:
    name: batch_test
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group_id: batch_test
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-internal: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
