DROP TABLE person IF EXISTS;

CREATE TABLE person  (
    person_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20),
    address VARCHAR(100)
);

DROP TABLE User IF EXISTS;
CREATE TABLE User (
    id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(20),
    type VARCHAR(20)
);

INSERT INTO User values (1, 'test', 'ADMIN');

CREATE TABLE TrainLine (
    lineName VARCHAR(20),
    startPositionName VARCHAR(100),
    destinationName VARCHAR(100),
    price NUMERIC(10,2),
    startTime VARCHAR(20),
    arriveTime VARCHAR(20)
);

INSERT INTO TrainLine values('D35', 'Dalian', 'Panjin', 91, '10:50', '12:30');


CREATE TABLE TicketBalance (
    id int,
    lineName VARCHAR(20),
    seatABalance int,
    seatBBalance int,
    seatCBalance int,
    seatEBalance int,
    seatFBalance int,
    day VARCHAR(20)
);
INSERT INTO TicketBalance values(1, 'D35', 100, 100, 100, 100, 100, '2020-01-20');

CREATE TABLE TicketBalanceDetail(
    id int,
    seatType VARCHAR(20),
    coach1 int,
    coach2 int,
    coach3 int,
    coach4 int,
    coach5 int,
    coach6 int,
    coach7 int,
    coach8 int,
    coach9 int,
    coach10 int
);
INSERT INTO TicketBalanceDetail values(1, 'A', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);
INSERT INTO TicketBalanceDetail values(1, 'B', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);
INSERT INTO TicketBalanceDetail values(1, 'C', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);
INSERT INTO TicketBalanceDetail values(1, 'E', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);
INSERT INTO TicketBalanceDetail values(1, 'F', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);

CREATE TABLE TicketRecord (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (start with 1),
    requestId VARCHAR(50),
    buyer VARCHAR(20),
    lineName VARCHAR(20),
    passenger VARCHAR(20),
    startPosition VARCHAR(100),
    destination VARCHAR(100),
    seatNum VARCHAR(10),
    coachNum int,
    createTime timestamp,
    status VARCHAR(10)
);