DROP TABLE person IF EXISTS;

CREATE TABLE person  (
    person_id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(20),
    last_name VARCHAR(20),
    address VARCHAR(100)
);

DROP TABLE User IF EXISTS;
CREATE TABLE User (
    id BIGINT IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(20),
    type VARCHAR(20)
);

INSERT INTO User values (1, 'test', 'ADMIN');

CREATE TABLE TicketRecord (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (start with 1),
    requestId VARCHAR(50),
    buyer VARCHAR(20),
    lineName VARCHAR(20),
    passenger VARCHAR(20),
    startPosition VARCHAR(100),
    destination VARCHAR(100),
    seatNum VARCHAR(10),
    coachNum int,
    createTime timestamp,
    status VARCHAR(10)
);

CREATE TABLE TrainLine (
    lineName VARCHAR(20),
    startPositionName VARCHAR(100),
    destinationName VARCHAR(100),
    price NUMERIC(10,2),
    startTime VARCHAR(20),
    arriveTime VARCHAR(20)
);

INSERT INTO TrainLine values('D35', 'Dalian', 'Panjin', 91, '10:50', '12:30');


CREATE TABLE TicketBalance (
    id int,
    lineName VARCHAR(20),
    seatABalance int,
    seatBBalance int,
    seatCBalance int,
    seatEBalance int,
    seatFBalance int,
    day VARCHAR(20)
);
INSERT INTO TicketBalance values(1, 'D35', 100, 100, 100, 100, 100, '2020-01-20');

CREATE TABLE TicketBalanceDetail(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (start with 1),
    ticketBalanceId int,
    seatType VARCHAR(20),
    coach1 int,
    coach2 int,
    coach3 int,
    coach4 int,
    coach5 int,
    coach6 int,
    coach7 int,
    coach8 int,
    coach9 int,
    coach10 int
);
INSERT INTO TicketBalanceDetail(id, ticketBalanceId, seatType, coach1, coach2, coach3, coach4, coach5, coach6, coach7, coach8, coach9, coach10) values(1, 1, 'A', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);
INSERT INTO TicketBalanceDetail(id, ticketBalanceId, seatType, coach1, coach2, coach3, coach4, coach5, coach6, coach7, coach8, coach9, coach10) values(2, 1, 'B', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);
INSERT INTO TicketBalanceDetail(id, ticketBalanceId, seatType, coach1, coach2, coach3, coach4, coach5, coach6, coach7, coach8, coach9, coach10) values(3, 1, 'C', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);
INSERT INTO TicketBalanceDetail(id, ticketBalanceId, seatType, coach1, coach2, coach3, coach4, coach5, coach6, coach7, coach8, coach9, coach10) values(4, 1, 'E', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);
INSERT INTO TicketBalanceDetail(id, ticketBalanceId, seatType, coach1, coach2, coach3, coach4, coach5, coach6, coach7, coach8, coach9, coach10) values(5, 1, 'F', 10, 10, 10, 10, 10, 10, 10, 10, 10, 10);

CREATE TABLE TicketBalanceCoachDetail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (start with 1),
    ticketBalanceDetailId int,
    coach int,
    row1 int,
    row2 int,
    row3 int,
    row4 int,
    row5 int,
    row6 int,
    row7 int,
    row8 int,
    row9 int,
    row10 int
);

INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(1, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 1,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 2,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 3,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 4,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 5,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 6,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 7,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 8,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 9,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(2, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 1,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 2,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 3,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 4,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 5,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 6,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 7,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 8,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 9,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(3, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 1,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 2,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 3,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 4,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 5,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 6,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 7,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 8,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 9,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(4, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 1,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 2,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 3,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 4,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 5,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 6,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 7,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 8,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 9,  0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO TicketBalanceCoachDetail(ticketBalanceDetailId, coach, row1, row2,row3, row4, row5, row6, row7, row8, row9, row10) values(5, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

